pipeline {
    agent any

    environment {
        // Docker image name
        IMAGE_NAME = 'my-app-image'
        // Docker container name
        CONTAINER_NAME = 'my-app-container'
        // Directory where the project is located
        PROJECT_DIR = 'app'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
                git url: 'https://github.com/danghh333/Final-Thesis.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to the project directory
                    dir(PROJECT_DIR) {
                        // Build the Docker image
                        sh "docker build -t ${IMAGE_NAME} ."
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove the container if it already exists
                    sh "docker stop ${CONTAINER_NAME} || true"
                    sh "docker rm ${CONTAINER_NAME} || true"

                    // Run the Docker container
                    sh """
                    docker run -d --name ${CONTAINER_NAME} \
                    -p 80:80 \
                    -v ${WORKSPACE}/${PROJECT_DIR}/static:/app/static \
                    ${IMAGE_NAME}
                    """
                }
            }
        }
    }

    post {
        always {
            // Clean up old Docker images
            sh 'docker image prune -f'
        }

        success {
            echo 'Deployment succeeded!'
        }

        failure {
            echo 'Deployment failed!'
        }
    }
}
